/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/home/charts/BarChart.vue')['default']
    DoughnutChart: typeof import('./components/home/charts/DoughnutChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/home/charts/LineChart.vue')['default']
    LogCard: typeof import('./components/logs/LogCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SleepWidget: typeof import('./components/home/widgets/SleepWidget.vue')['default']
    StepsWidget: typeof import('./components/home/widgets/StepsWidget.vue')['default']
    WaterWidget: typeof import('./components/home/widgets/WaterWidget.vue')['default']
  }
}
